### ISSUE TITLE
Null pointer argument in call to CFRetain

### ISSUE THREAD

**Issue by hw20101101** [wezm/RegexKitLite#1]
RegexKitLite.m  
row 1104 :   cachedRegex->setToString  = (CFStringRef)CFRetain((CFTypeRef)matchString);

http://7xqvz3.com1.z0.glb.clouddn.com/201603QQ20160307-3.png

**Comment by wezm** [comment]
This is an (outdated) mirror of the official code. I suggest ensuring you're using the most recent version of the code and if the issue still occurs create an issue on the project: http://regexkit.sourceforge.net

Also note that there is built in regular expression support in iOS and OS X now: https://developer.apple.com/library/ios/documentation/Foundation/Reference/NSRegularExpression_Class/index.html#//apple_ref/occ/cl/NSRegularExpression
