### ISSUE TITLE
dlsym() is a private function that Apple forbidden to use

### ISSUE THREAD

**Issue by LustySwimmer** [wezm/RegexKitLite#2]
Hello!
In Apple's Review Guideline 2.5.2,it's already forbidden to use dlsym()、dlopen() function as they are consider as private API,but I found that dlsym() is used in RegexKitLite,could you please remove any founction that depend on dlsym()? Thank you very much!

**Comment by wezm** [comment]
Hi, this is a (very stale) mirror of the real [RegexKitLite](http://regexkit.sourceforge.net/) package that hasn't been updated in about 7 years. iOS now includes regular expression support in the framework so this probably shouldn't even be needed any more.
